version: "3.8"

services:
  auth:
    build:
      dockerfile: docker/auth/Dockerfile
      context: .
    image: koh-auth-app
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - docker/auth/.env
  mail:
    build:
      dockerfile: docker/mail/Dockerfile
      context: .
    image: koh-mail-app
    ports:
      -