package koh.service.gateway.kafka;

public enum KafkaRespTopic {
    TOPIC_AUTH_GUEST_RESPONSE,
    TOPIC_AUTH_LOGIN_RESPONSE,
    TOPIC_AUTH_REFRESH_RESPONSE,
    TOPIC_AUTH_REGISTER_RESPONSE,
    TOPIC_VPS_PROVIDER_CREATE_VOLUME_RESPONSE,
    TOPIC_VPS_PROVIDER_CREATE_IMAGE_RESPONSE,
    TOPIC_VPS_PROVIDER_CREATE_NETWORK_RESPONSE,
    TOPIC_VPS_PROVIDER_CREATE_CONTAINER_RESPONSE,
    TOPIC_VPS_PROVIDER_START_CONTAINER_RESPONSE,
    TOPIC_VPS_PROVIDER_STOP_CONTAINER_RESPONSE
}
